apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: gadget
spec:
  caveats: |
    Inspektor Gadget needs to be deployed to each node:

    $ kubectl gadget deploy | kubectl apply -f -

    Read the documentation available at https://github.com/kinvolk/inspektor-gadget
    to get more information about the server side installation process.
  description: |
    Inspektor Gadget is a collection of tools (or gadgets) for developers of
    Kubernetes applications.

    Inspektor Gadget is deployed to each node as a privileged DaemonSet.
    It uses in-kernel BPF helper programs to monitor events mainly related to
    syscalls from userspace programs in a pod. The BPF programs are run by
    the kernel and gather the log data. Inspektor Gadget's userspace utilities
    fetch the log data from ring buffers and display it. What BPF programs are
    and how Inspektor Gadget uses them is briefly explained in the architecture
    document:
    https://github.com/kinvolk/inspektor-gadget/blob/main/docs/architecture.md
  homepage: https://github.com/kinvolk/inspektor-gadget
  platforms:
  - bin: kubectl-gadget
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: c796f2e45b8d72dca78cf02eb28558597d899c6b07779cfeb897bf524283c808
    uri: https://github.com/kinvolk/inspektor-gadget/releases/download/v0.4.2/inspektor-gadget-linux-amd64.tar.gz
  - bin: kubectl-gadget
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: 9a8ae75b2586fae232cea5dc21c8415ff02b7b6b79085895604c7d0af917d3e5
    uri: https://github.com/kinvolk/inspektor-gadget/releases/download/v0.4.2/inspektor-gadget-linux-arm64.tar.gz
  - bin: kubectl-gadget
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: df8c6d6feccd9c2b4b03bd35d699bb47c2e4878949bc769e9b673ce49a68fa8f
    uri: https://github.com/kinvolk/inspektor-gadget/releases/download/v0.4.2/inspektor-gadget-darwin-amd64.tar.gz
  - bin: kubectl-gadget
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: bb45fbc47777fb7c1e92aa54c11c9c7a9d0cdfbf4304017ffbd400f4618d7069
    uri: https://github.com/kinvolk/inspektor-gadget/releases/download/v0.4.2/inspektor-gadget-darwin-arm64.tar.gz
  - bin: kubectl-gadget
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: e94f2b7f5235137c15cda557e3177748478ad1c86792e25a6584d1ff9b1f9238
    uri: https://github.com/kinvolk/inspektor-gadget/releases/download/v0.4.2/inspektor-gadget-windows-amd64.tar.gz
  shortDescription: Gadgets for debugging and introspecting apps
  version: v0.4.2
