apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: prompt
spec:
  caveats: |
    This plugin requires bash.
    When removing this plugin, delete the line beginning with `function kubectl()` and `KUBECTL_*_PROMPT` in your ~/.bash_profile.
  description: |
    Protect your production environments!
    When issuing certain commands inside a specified namespace/cluster, a warning prompt will appear.
    This will alert the user that they are in a flagged environment and require a confirmation before executing the command.
    See `https://github.com/jordanwilson230/kubectl-plugins#kubectl-prompt` for documentation.
    Usage:
        View description)            kubectl prompt
        Flag a namespace)            kubectl prompt add -n production
        Flag a cluster)              kubectl prompt add -c my-production-cluster
        View flagged environments)   kubectl prompt list
  homepage: https://github.com/jordanwilson230/kubectl-plugins/tree/krew#kubectl-prompt
  platforms:
  - bin: kubectl-prompt
    files:
    - from: '*/kubectl-prompt'
      to: .
    - from: '**/LICENSE'
      to: .
    selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    sha256: e0bae378c0cf049526cc8d45d3389d78f7054bc5cfc5de24bd41b184ce9e806c
    uri: https://github.com/jordanwilson230/kubectl-plugins/archive/v1.0.3-krew.zip
  shortDescription: Prompts for user confirmation when executing commands in critical
    namespaces or clusters, i.e., production.
  version: v1.0.3-krew
