apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: score
spec:
  description: Kubernetes object analysis with recommendations for improved reliability
    and security.
  homepage: https://github.com/zegl/kube-score
  platforms:
  - bin: kube-score
    files:
    - from: kube-score
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
    sha256: 534d6a74d1c801e926ec6fd0987f4f417d7e828b75baec005157b63c2a3de5d9
    uri: https://github.com/zegl/kube-score/releases/download/v1.10.0/kube-score_1.10.0_darwin_amd64.tar.gz
  - bin: kube-score
    files:
    - from: kube-score
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
    sha256: 1e0b1a0cef0b46a333ed084993ebefc2f20d983d7333a862704a16f68b085d96
    uri: https://github.com/zegl/kube-score/releases/download/v1.10.0/kube-score_1.10.0_linux_amd64.tar.gz
  shortDescription: Kubernetes static code analysis.
  version: v1.10.0
